/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sinavdenemeverikaydi;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author BLUE
 */

public class mainWind extends javax.swing.JFrame {
calculate cal=new calculate();
DbAccess database=new DbAccess();
removeData rm=new removeData();
    /**
     * Creates new form mainWind
     */
    public mainWind() {
        initComponents();
        this.setLocation(200, 100);
        turyan.setValue(0);
        matyan.setValue(0);
        taryan.setValue(0);
        cogyan.setValue(0);
        vatyan.setValue(0);
        turdog.setValue(0);
        matdog.setValue(0);
        tardog.setValue(0);
        cogdog.setValue(0);
        vatdog.setValue(0);
        gunCelle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        matnet = new javax.swing.JTextField();
        turnet = new javax.swing.JTextField();
        tarnet = new javax.swing.JTextField();
        cognet = new javax.swing.JTextField();
        vatnet = new javax.swing.JTextField();
        turkce = new javax.swing.JToggleButton();
        matematik = new javax.swing.JToggleButton();
        tarih = new javax.swing.JToggleButton();
        cografya = new javax.swing.JToggleButton();
        vatandaslik = new javax.swing.JToggleButton();
        deneme = new javax.swing.JToggleButton();
        jLabel9 = new javax.swing.JLabel();
        turdog = new javax.swing.JFormattedTextField();
        turyan = new javax.swing.JFormattedTextField();
        matdog = new javax.swing.JFormattedTextField();
        matyan = new javax.swing.JFormattedTextField();
        tardog = new javax.swing.JFormattedTextField();
        taryan = new javax.swing.JFormattedTextField();
        cogdog = new javax.swing.JFormattedTextField();
        cogyan = new javax.swing.JFormattedTextField();
        vatdog = new javax.swing.JFormattedTextField();
        vatyan = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        tabloyaekle = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        chartPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÜRKÇE");

        jLabel2.setText("MATEMATÝK");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("TARÝH");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("COÐRAFYA");

        jLabel5.setText("VATANDAÞLIK");

        jLabel6.setText("DOÐRU:");

        jLabel7.setText("YANLIÞ:");

        jLabel8.setText("NET:");

        matnet.setEditable(false);

        turnet.setEditable(false);

        tarnet.setEditable(false);

        cognet.setEditable(false);

        vatnet.setEditable(false);

        buttonGroup1.add(turkce);
        turkce.setText("TÜRKÇE");
        turkce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turkceActionPerformed(evt);
            }
        });

        buttonGroup1.add(matematik);
        matematik.setText("MATEMATÝK");
        matematik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matematikActionPerformed(evt);
            }
        });

        buttonGroup1.add(tarih);
        tarih.setText("TARÝH");
        tarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarihActionPerformed(evt);
            }
        });

        buttonGroup1.add(cografya);
        cografya.setText("COÐRAFYA");
        cografya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cografyaActionPerformed(evt);
            }
        });

        buttonGroup1.add(vatandaslik);
        vatandaslik.setText("VATANDAÞLIK");
        vatandaslik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vatandaslikActionPerformed(evt);
            }
        });

        buttonGroup1.add(deneme);
        deneme.setText("DENEME");
        deneme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                denemeActionPerformed(evt);
            }
        });

        jLabel9.setText("DURUM GRAFÝKLERÝ");

        turdog.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        turdog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                turdogKeyReleased(evt);
            }
        });

        turyan.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        turyan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                turyanKeyReleased(evt);
            }
        });

        matdog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matdogKeyReleased(evt);
            }
        });

        matyan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matyanKeyReleased(evt);
            }
        });

        tardog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tardogKeyReleased(evt);
            }
        });

        taryan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taryanKeyReleased(evt);
            }
        });

        cogdog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cogdogKeyReleased(evt);
            }
        });

        cogyan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cogyanKeyReleased(evt);
            }
        });

        vatdog.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vatdogKeyReleased(evt);
            }
        });

        vatyan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                vatyanKeyReleased(evt);
            }
        });

        tabloyaekle.setText("<html><center>TABLOYA<br> EKLE</center></html>");
        tabloyaekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tabloyaekleActionPerformed(evt);
            }
        });

        sil.setText("<html><center>DENEMEYÝ<br>SÝL</center></html>");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabloyaekle)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(sil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(tabloyaekle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sil)
                .addGap(1, 1, 1))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\BLUE\\Desktop\\1234.jpg")); // NOI18N
        jLabel10.setToolTipText("Programý Geliþtirenin Resmi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(turyan)
                    .addComponent(turdog)
                    .addComponent(turnet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2)
                    .addComponent(matyan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matdog, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(matnet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(taryan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tardog)
                    .addComponent(tarnet)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cogyan)
                    .addComponent(cogdog)
                    .addComponent(cognet)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vatdog, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(vatyan)
                            .addComponent(vatnet))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(matematik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(turkce, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deneme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vatandaslik, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cografya, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tarih, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addGap(60, 60, 60)))
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tarih)
                                            .addComponent(deneme))
                                        .addGap(0, 0, 0)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(turkce)
                                            .addComponent(cografya))
                                        .addGap(0, 0, 0)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(vatandaslik)
                                            .addComponent(matematik)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel6)
                                                    .addComponent(turdog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jLabel7)
                                                    .addComponent(turyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(matdog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(matyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(tardog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(taryan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(cogdog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(cogyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(vatyan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(vatdog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(3, 3, 3)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(matnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(turnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cognet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(vatnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DENEME NO", "", "TÜRKÇE", "MATEMARÝK", "TARÝH", "COÐRAFYA", "VATANDAÞLIK"
            }
        ));
        jTable1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(40);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );

        chartPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        chartPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chartPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chartPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void turdogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_turdogKeyReleased
if(turdog.getValue()==null||turdog.getText().equals("")){
turdog.setValue(0);
}else{
cal.setNet(Integer.parseInt(turdog.getText()),Integer.parseInt(turyan.getText()));
turnet.setText(String.valueOf(cal.getNet()));
}
// TODO add your handling code here:
    }//GEN-LAST:event_turdogKeyReleased

    private void turyanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_turyanKeyReleased
if(turyan.getValue()==null||turyan.getText().equals("")){
turyan.setValue(0);
}else{
cal.setNet(Integer.parseInt(turdog.getText()),Integer.parseInt(turyan.getText()));
turnet.setText(String.valueOf(cal.getNet()));
}        // TODO add your handling code here:
    }//GEN-LAST:event_turyanKeyReleased

    private void matdogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matdogKeyReleased
if(matdog.getValue()==null||matdog.getText().equals("")){
matdog.setValue(0);
}else{
cal.setNet(Integer.parseInt(matdog.getText()),Integer.parseInt(matyan.getText()));
matnet.setText(String.valueOf(cal.getNet()));}  // TODO add your handling code here:
    }//GEN-LAST:event_matdogKeyReleased

    private void matyanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matyanKeyReleased
if(matyan.getValue()==null||matyan.getText().equals("")){
matyan.setValue(0);
}else{
cal.setNet(Integer.parseInt(matdog.getText()),Integer.parseInt(matyan.getText()));
matnet.setText(String.valueOf(cal.getNet()));}   // TODO add your handling code here:
    }//GEN-LAST:event_matyanKeyReleased

    private void tardogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tardogKeyReleased
if(tardog.getValue()==null||tardog.getText().equals("")){
tardog.setValue(0);
}else{
cal.setNet(Integer.parseInt(tardog.getText()),Integer.parseInt(taryan.getText()));
tarnet.setText(String.valueOf(cal.getNet()));}    // TODO add your handling code here:
    }//GEN-LAST:event_tardogKeyReleased

    private void taryanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taryanKeyReleased
if(taryan.getValue()==null||taryan.getText().equals("")){
taryan.setValue(0);
}else{
cal.setNet(Integer.parseInt(tardog.getText()),Integer.parseInt(taryan.getText()));
tarnet.setText(String.valueOf(cal.getNet()));}  // TODO add your handling code here:
    }//GEN-LAST:event_taryanKeyReleased

    private void cogdogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cogdogKeyReleased
if(cogdog.getValue()==null||cogdog.getText().equals("")){
cogdog.setValue(0);
}else{        
cal.setNet(Integer.parseInt(cogdog.getText()),Integer.parseInt(cogyan.getText()));
cognet.setText(String.valueOf(cal.getNet()));}        // TODO add your handling code here:
    }//GEN-LAST:event_cogdogKeyReleased

    private void cogyanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cogyanKeyReleased
if(cogyan.getValue()==null||cogyan.getText().equals("")){
cogyan.setValue(0);
}else{        
cal.setNet(Integer.parseInt(cogdog.getText()),Integer.parseInt(cogyan.getText()));
cognet.setText(String.valueOf(cal.getNet()));}  // TODO add your handling code here:
    }//GEN-LAST:event_cogyanKeyReleased

    private void vatdogKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vatdogKeyReleased
if(vatdog.getValue()==null||vatdog.getText().equals("")){
vatdog.setValue(0);
}else{
    cal.setNet(Integer.parseInt(vatdog.getText()),Integer.parseInt(vatyan.getText()));
vatnet.setText(String.valueOf(cal.getNet()));}        // TODO add your handling code here:
    }//GEN-LAST:event_vatdogKeyReleased

    private void vatyanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vatyanKeyReleased
if(vatyan.getValue()==null||vatyan.getText().equals("")){
vatyan.setValue(0);
}else{
    cal.setNet(Integer.parseInt(vatdog.getText()),Integer.parseInt(vatyan.getText()));
vatnet.setText(String.valueOf(cal.getNet()));}        // TODO add your handling code here:
    }//GEN-LAST:event_vatyanKeyReleased

    private void tabloyaekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tabloyaekleActionPerformed
       DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
        database.openDatabase();
        int str = 1;
               try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {
                str=Integer.parseInt(rs.getString("deneme"))+1;
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
String addRow = "INSERT INTO veritablosu (deneme,turdogru,turyanlis,turnet,"
        + "matdogru,matyanlis,matnet,"
        + "tardogru,taryanlis,tarnet,"
        + "cogdogru,cogyanlis,cognet,"
        + "vatdogru,vatyanlis,vatnet"
        + ")"
  + "VALUES('"+str+"','"+turdog.getText()+"','"+turyan.getText()+"','"+turnet.getText()+"'"
        + ",'"+matdog.getText()+"','"+matyan.getText()+"','"+matnet.getText()+"'"
        + ",'"+tardog.getText()+"','"+taryan.getText()+"','"+tarnet.getText()+"'"
        + ",'"+cogdog.getText()+"','"+cogyan.getText()+"','"+cognet.getText()+"'"
        + ",'"+vatdog.getText()+"','"+vatyan.getText()+"','"+vatnet.getText()+"'"
        + ")";  
try {
            database.s.execute(addRow);         
            JOptionPane.showMessageDialog(null,"Bilgiler kaydedildi.");
        } catch (SQLException ex) {
            Logger.getLogger(DbAccess.class.getName()).log(Level.SEVERE, null, ex);
        }
database.closeDatabase();
rm.setData(model6);
gunCelle();
turdog.setValue(0);
turyan.setValue(0);
turnet.setText("");
matdog.setValue(0);
matyan.setValue(0);
matnet.setText("");
tardog.setValue(0);
taryan.setValue(0);
tarnet.setText("");
cogdog.setValue(0);
cogyan.setValue(0);
cognet.setText("");
vatdog.setValue(0);
vatyan.setValue(0);
vatnet.setText("");

// TODO add your handling code here:
    }//GEN-LAST:event_tabloyaekleActionPerformed

    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();       
        if(jTable1.getSelectedRow()!=-1){
       int result = JOptionPane.showOptionDialog(null, 
        (String)jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0)+" Nolu Deneme Sýnavýný SÝLMEK istediðinize eminmisiniz.", 
        "Feedback", 
        JOptionPane.OK_CANCEL_OPTION, 
        JOptionPane.WARNING_MESSAGE, 
        null, 
      new String[]{"EVET", "HAYIR"}, // this is the array
        "default");
      if (result == JOptionPane.OK_OPTION){
        database.openDatabase();
        try{
            String addRow ="DELETE FROM veritablosu WHERE deneme='"+(String)model6.getValueAt(jTable1.getSelectedRow(),0)+"'";
            database.s.executeUpdate(addRow);
           
        } catch (SQLException ex) {
            Logger.getLogger(DbAccess.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
      }else{
            JOptionPane.showMessageDialog(null, "Lütfen silmek istediðiniz Deneme Sýnavýný seçiniz.");
        }
     database.closeDatabase();
      rm.setData(model6);
     gunCelle();
// TODO add your handling code here:
    }//GEN-LAST:event_silActionPerformed

    private void denemeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_denemeActionPerformed
DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
double rs1,rs2,rs3,rs4,rs5;
              database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {   
                rs1=Double.valueOf(rs.getString("turnet"));
                rs2=Double.valueOf(rs.getString("matnet"));
                rs3=Double.valueOf(rs.getString("tarnet"));
                rs4=Double.valueOf(rs.getString("cognet"));
                rs5=Double.valueOf(rs.getString("vatnet"));
                barchartdata.setValue(rs1+rs2+rs3+rs4+rs5, "net sayýsý", rs.getString("deneme"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
       /*barchartdata.setValue(200, "bune", "kasým");
       barchartdata.setValue(150, "bune", "aralýk");
       barchartdata.setValue(250, "bune", "ocak");*/
JFreeChart barchart= ChartFactory.createBarChart("Sýnav Ýstatistiði", "Deneme Sayýsý", "Soru Sayýsý", barchartdata, PlotOrientation.VERTICAL, false, true, false);
CategoryPlot barchrt=barchart.getCategoryPlot();
barchrt.setRangeGridlinePaint(Color.ORANGE);

ChartPanel barpanel = new ChartPanel(barchart);
chartPanel.removeAll();
chartPanel.add(barpanel,BorderLayout.CENTER);
chartPanel.validate();
rm.setData(model6);
gunCelle();
// TODO add your handling code here:
    }//GEN-LAST:event_denemeActionPerformed

    private void turkceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkceActionPerformed
   
        DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        rm.setData(model6);
double rs1;
              database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {  
                String str=rs.getString("deneme");
                rs1=Double.valueOf(rs.getString("turnet"));
                barchartdata.setValue(rs1, "net sayýsý", str);
                model6.addRow(new Object[]{str,"NET",rs1});
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
       /*barchartdata.setValue(200, "bune", "kasým");
       barchartdata.setValue(150, "bune", "aralýk");
       barchartdata.setValue(250, "bune", "ocak");*/
JFreeChart barchart= ChartFactory.createBarChart("Sýnav Ýstatistiði", "Deneme Sayýsý", "Soru Sayýsý", barchartdata, PlotOrientation.VERTICAL, false, true, false);
CategoryPlot barchrt=barchart.getCategoryPlot();
barchrt.setRangeGridlinePaint(Color.ORANGE);

ChartPanel barpanel = new ChartPanel(barchart);
chartPanel.removeAll();
chartPanel.add(barpanel,BorderLayout.CENTER);
chartPanel.validate();   // TODO add your handling code here:
    }//GEN-LAST:event_turkceActionPerformed

    private void matematikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matematikActionPerformed
     DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
        DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
        rm.setData(model6);
double rs2;
              database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {   String str=rs.getString("deneme");
                rs2=Double.valueOf(rs.getString("matnet"));
                barchartdata.setValue(rs2, "net sayýsý", str);
                 model6.addRow(new Object[]{str,"NET","",rs2});
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
       /*barchartdata.setValue(200, "bune", "kasým");
       barchartdata.setValue(150, "bune", "aralýk");
       barchartdata.setValue(250, "bune", "ocak");*/
JFreeChart barchart= ChartFactory.createBarChart("Sýnav Ýstatistiði", "Deneme Sayýsý", "Soru Sayýsý", barchartdata, PlotOrientation.VERTICAL, false, true, false);
CategoryPlot barchrt=barchart.getCategoryPlot();
barchrt.setRangeGridlinePaint(Color.ORANGE);

ChartPanel barpanel = new ChartPanel(barchart);
chartPanel.removeAll();
chartPanel.add(barpanel,BorderLayout.CENTER);
chartPanel.validate();         // TODO add your handling code here:
    }//GEN-LAST:event_matematikActionPerformed

    private void tarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarihActionPerformed
    DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
     DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
     rm.setData(model6);
double rs3;
              database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {   
                String str=rs.getString("deneme");
                rs3=Double.valueOf(rs.getString("tarnet"));
                barchartdata.setValue(rs3, "net sayýsý", str);
                model6.addRow(new Object[]{str,"NET","","",rs3});
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
       /*barchartdata.setValue(200, "bune", "kasým");
       barchartdata.setValue(150, "bune", "aralýk");
       barchartdata.setValue(250, "bune", "ocak");*/
JFreeChart barchart= ChartFactory.createBarChart("Sýnav Ýstatistiði", "Deneme Sayýsý", "Soru Sayýsý", barchartdata, PlotOrientation.VERTICAL, false, true, false);
CategoryPlot barchrt=barchart.getCategoryPlot();
barchrt.setRangeGridlinePaint(Color.ORANGE);

ChartPanel barpanel = new ChartPanel(barchart);
chartPanel.removeAll();
chartPanel.add(barpanel,BorderLayout.CENTER);
chartPanel.validate();         // TODO add your handling code here:
    }//GEN-LAST:event_tarihActionPerformed

    private void cografyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cografyaActionPerformed
     DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
     DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
     rm.setData(model6);
double rs4;
              database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {   
                String str=rs.getString("deneme");
                rs4=Double.valueOf(rs.getString("cognet"));
                barchartdata.setValue(rs4, "net sayýsý", str);
                 model6.addRow(new Object[]{str,"NET","","","",rs4});
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
       /*barchartdata.setValue(200, "bune", "kasým");
       barchartdata.setValue(150, "bune", "aralýk");
       barchartdata.setValue(250, "bune", "ocak");*/
JFreeChart barchart= ChartFactory.createBarChart("Sýnav Ýstatistiði", "Deneme Sayýsý", "Soru Sayýsý", barchartdata, PlotOrientation.VERTICAL, false, true, false);
CategoryPlot barchrt=barchart.getCategoryPlot();
barchrt.setRangeGridlinePaint(Color.ORANGE);

ChartPanel barpanel = new ChartPanel(barchart);
chartPanel.removeAll();
chartPanel.add(barpanel,BorderLayout.CENTER);
chartPanel.validate();         // TODO add your handling code here:
    }//GEN-LAST:event_cografyaActionPerformed

    private void vatandaslikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vatandaslikActionPerformed
     DefaultCategoryDataset barchartdata = new DefaultCategoryDataset();
          DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
     rm.setData(model6);
double rs5;
              database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {   
                String str=rs.getString("deneme");
                rs5=Double.valueOf(rs.getString("vatnet"));
                barchartdata.setValue(rs5, "net sayýsý", str);
                model6.addRow(new Object[]{str,"NET","","","","",rs5});
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
       /*barchartdata.setValue(200, "bune", "kasým");
       barchartdata.setValue(150, "bune", "aralýk");
       barchartdata.setValue(250, "bune", "ocak");*/
JFreeChart barchart= ChartFactory.createBarChart("Sýnav Ýstatistiði", "Deneme Sayýsý", "Soru Sayýsý", barchartdata, PlotOrientation.VERTICAL, false, true, false);
CategoryPlot barchrt=barchart.getCategoryPlot();
barchrt.setRangeGridlinePaint(Color.ORANGE);

ChartPanel barpanel = new ChartPanel(barchart);
chartPanel.removeAll();
chartPanel.add(barpanel,BorderLayout.CENTER);
chartPanel.validate();         // TODO add your handling code here:
    }//GEN-LAST:event_vatandaslikActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainWind.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWind().setVisible(true);
                            }
        });
    }
 public void gunCelle(){
    
    DefaultTableModel model6 = (DefaultTableModel)jTable1.getModel();
        //jTable6.getModel().getValueAt(row_index, col_index);
      database.openDatabase();
    try {
            String firTable = "SELECT * FROM veritablosu ";
            database.s.execute(firTable);
            ResultSet rs = database.s.getResultSet();
            while((rs!=null) && (rs.next()))
            {
                String str=rs.getString("deneme");
              model6.addRow(new Object[]{str,"DOÐRU",rs.getString("turdogru"),rs.getString("matdogru"),rs.getString("tardogru"),rs.getString("cogdogru"),rs.getString("vatdogru")});
            model6.addRow(new Object[]{str,"YANLÝÞ",rs.getString("turyanlis"),rs.getString("matyanlis"),rs.getString("taryanlis"),rs.getString("cogyanlis"),rs.getString("vatyanlis")});
           model6.addRow(new Object[]{str,"NET",rs.getString("turnet"),rs.getString("matnet"),rs.getString("tarnet"),rs.getString("cognet"),rs.getString("vatnet")});
            }
        } catch (SQLException ex) {
            Logger.getLogger(mainWind.class.getName()).log(Level.SEVERE, null, ex);
        }
       database.closeDatabase();
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel chartPanel;
    private javax.swing.JFormattedTextField cogdog;
    private javax.swing.JTextField cognet;
    private javax.swing.JToggleButton cografya;
    private javax.swing.JFormattedTextField cogyan;
    private javax.swing.JToggleButton deneme;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField matdog;
    private javax.swing.JToggleButton matematik;
    private javax.swing.JTextField matnet;
    private javax.swing.JFormattedTextField matyan;
    private javax.swing.JButton sil;
    private javax.swing.JButton tabloyaekle;
    private javax.swing.JFormattedTextField tardog;
    private javax.swing.JToggleButton tarih;
    private javax.swing.JTextField tarnet;
    private javax.swing.JFormattedTextField taryan;
    private javax.swing.JFormattedTextField turdog;
    private javax.swing.JToggleButton turkce;
    private javax.swing.JTextField turnet;
    private javax.swing.JFormattedTextField turyan;
    private javax.swing.JToggleButton vatandaslik;
    private javax.swing.JFormattedTextField vatdog;
    private javax.swing.JTextField vatnet;
    private javax.swing.JFormattedTextField vatyan;
    // End of variables declaration//GEN-END:variables
}
